### ISSUE TITLE
add streamer classes to library

### ISSUE THREAD

**Issue by glyphard** [veritacodex/TastyTrade.Api.Client#11]
the FuturesStreamer, OptionStreamer, and AccountStreamer are pretty handy to have when building an application.  While they're not strictly part of an 'api client' they would be handy to have available either in a namespace within the api client pkg, or as a separate small package that depends on the api package.

**Comment by veritacodex** [comment]
We would need to maintain two libraries, with the consequent pushes to Nuget and their shenanigans. 
Also, manage dependencies and all of those fun tasks.

There's no harm in including the whole library as it is.
