### ISSUE TITLE
sonar cloud build is failing

### ISSUE THREAD

**Issue by glyphard** [veritacodex/TastyTrade.Api.Client#8]
may be as simple as not having a sonar token:

    19 Warning(s)
    0 Error(s)

Time Elapsed 00:00:35.63

Workload updates are available. Run `dotnet workload list` for more information.
SonarScanner for MSBuild 9.0.2
Using the .NET Core version of the Scanner for MSBuild
**The format of the analysis property sonar.token= is invalid**

**Comment by veritacodex** [comment]
It is not an issue when the code gets merged.

Don't worry too much about these types of issues, I will tidy things up when I see the report.
